### ISSUE TITLE
New OSC based version (No MIDI)

### ISSUE THREAD

**Issue by buggyboy** [carlfriedrich/TotalKeyMix#2]
Hi carlfriedrich,

not an issue, but I thought you might be interested in this post (and could'nt think of another way to get in touch with you) :
https://www.autohotkey.com/boards/viewtopic.php?p=473910#p473910
I wanted to know if you would like to include my changes re:OSC in your code and continue to maintain TotalkeyMix from there?
I'll post in that thread the code and what has to be known about it in the next few days.
Cheers,
Benoît

**Comment by carlfriedrich** [comment]
@buggyboy
Hi Benoît, thanks a lot for your comment! Funny thing, actually I was already planning on doing this modification myself in the near future. 😁 So yes, I would totally love to integrate your changes!
The easiest way would be if you fork this repo, push your changes to a branch and open a pull request here on GitHub. If you're not familiar with Git or GitHub, though, I can as well pull the code from the AHK board. I am watching that thread, so if you're posting over there, I will be notified.
Thanks a lot, looking forward to it!
Cheers,
Tim
